var vm=new Vue({
	el:".container",
	data:{
		addressList:[],//地址列表
		limitNum:3,//限制显示几条数据
		current:0,//当前地址索引
		moreFlag:false,
		selectType:1,//配送方式
		showModalOverLay:false,//展示遮罩
		isShowModal:false,//是否展示确认框
		isShowEditModal:false,//是否展示编辑弹出框
		currentAddress:""
	},
	/*挂载*/
	mounted:function(){
		this.$nextTick(function () {
			this.getAddressListData();
		});
	},
	/*计算属性*/
	computed:{
		/*切割显示的地址数据*/
		limitAddressList:function(){
//			这种用法错误,slice切割数组返回的是新数组,不改变原数组,而赋值后会导致原数组也发生变化
//			return this.addressList=this.addressList.slice(0,this.limitNum);
			return this.addressList.slice(0,this.limitNum);
		}
	},
	methods:{
		/*获取数据*/
		getAddressListData:function(){
			//地址前不能加/
			axios.get("data/address.json").then(res=>{
				this.addressList=res.data.result;
			},err=>{
				alert(err.message);
			});
		},
		/*设置默认地址*/
		setDefault:function(item){
			this.addressList.forEach((item,index)=>{
				if(index != this.current){
					item.isDefault=false;
				}else{
					item.isDefault=true; 
				}
			});
		},
		/*展示更多/收起*/
		moreLoad:function(){
			this.moreFlag=!this.moreFlag;
			if(this.moreFlag){
				this.limitNum=this.addressList.length;
			}else{
				this.limitNum=3;
			}
		},
		/*删除btn*/
		delBtn:function(item){
			this.showModalOverLay=true;
			this.isShowModal=true;
			this.currentAddress=item;
		},
		/*确认删除地址*/
		delAddress:function(item){
			this.addressList.splice(item,1);
			this.isShowModal=false;
			this.showModalOverLay=false;
		},
		/*取消删除*/
		cancleDel:function(){
			this.isShowModal=false;
			this.showModalOverLay=false;
		},
		/*编辑Btn*/
		editBtn:function(item){
			this.showModalOverLay=true;
			this.isShowEditModal=true;
			this.currentAddress=item;
		},
		/*取消编辑*/
		cancleEdit:function(){
			this.isShowEditModal=false;
			this.showModalOverLay=false;
		},
		edit:function(){
			this.addressList.forEach((item,index)=>{
				if(item.addressId==this.currentAddress.addressId){
					item=this.currentAddress;
					this.cancleEdit();
				}
			});
		}
	}
});